# Mark Monitor SFTP Example COnfiguration
#
markmonitor_ssh_user: test

markmonitor_ssh_password: test

markmonitor_ssh_host: http://localhost

markmonitor_ssh_port: 9090

markmonitor_ssl_hostkey: abcdefg1234567890

# markmonitor_ssl_cert_algorithm:

# markmonitor_ssl_signature:

# markmonitor_sftp_pkt_size: 

markmonitor_dns_master_ips:
  - 1.2.3.4
  - 5.6.7.8 

markmonitor_registrar_domain_filepath: ./domainconfig

markmonitor_temp_file_folder: /tmp

